version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: roommate_postgres
    restart: always
    environment:
      POSTGRES_USER: roommate_user
      POSTGRES_PASSWORD: roommate_password
      POSTGRES_DB: roommate_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: